#!/bin/sh

NAME=`echo $1 | sed "s/\.tex//g"`

if [ "$NAME" = "" ]
then
  echo " "
  echo "please supply tex file name as first argument"
  echo " "
  exit 1
fi

if [ ! -d ../Illustrations ]; then
  echo " "
  echo "please check out DQM/domain/doc/Illustrations as ../Illustrations"
  echo " "
  exit 1
fi

(set -e
 mkdir -p Snippets
 cd Snippets
 for f in ../../Illustrations/*.{png,pdf}; do
   [ -f "$f" ]
   dest=$(basename "$f" | tr ' ' _)
   [ -L "$dest" ] || ln -s "$f" "$dest"
   case $dest in *.png ) ebb "$dest" ;; esac
 done) || exit 1

latex          $NAME.tex </dev/null
bibtex         $NAME
makeindex      $NAME
makeindex      -o $NAME.aind $NAME.aidx
latex          $NAME.tex </dev/null
latex          $NAME.tex </dev/null
#dvips          -o $NAME.ps $NAME.dvi
dvipdfmx -V 6  -o $NAME.pdf $NAME.dvi
#dvipdfm -V 5  -o $NAME.pdf $NAME.dvi

rm -f $NAME.aind
rm -f $NAME.ind
rm -f $NAME.ilg
rm -f $NAME.KUIP
rm -f $NAME.aux
rm -f $NAME.aidx
rm -f $NAME.idx
rm -f $NAME.lof
rm -f $NAME.lot
rm -f $NAME.log
rm -f $NAME.dvi
rm -f $NAME.toc
rm -f $NAME.blg
rm -f $NAME.bbl
rm -f $NAME.out
rm -f texput.log
rm -f missfont.log
rm -fr Snippets
